function Hd = fix_filter
%FIX_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the DSP System Toolbox 8.5.
% Generated on: 08-May-2014 13:49:59

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 8;  % Sampling Frequency

N     = 31;   % Order
Fpass = 1.6;  % Passband Frequency
Fstop = 2.4;  % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 50;   % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);
% Set the arithmetic property.
set(Hd, 'Arithmetic', 'fixed', ...
    'CoeffWordLength', 11, ...
    'CoeffAutoScale', true, ...
    'Signed',         true, ...
    'InputWordLength', 16, ...
    'inputFracLength', 15, ...
    'FilterInternals',  'FullPrecision');
denormalize(Hd);


% [EOF]
